// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'keyhere',
    appId: '1:1018622800124:web:9bcc1e49153defb3f5a779',
    messagingSenderId: '1018622800124',
    projectId: 'fir-connection-bd828',
    authDomain: 'fir-connection-bd828.firebaseapp.com',
    storageBucket: 'fir-connection-bd828.appspot.com',
    measurementId: 'G-NZ822X9GF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'keyhere',
    appId: '1:1018622800124:android:627b6b902fe97bc3f5a779',
    messagingSenderId: '1018622800124',
    projectId: 'fir-connection-bd828',
    storageBucket: 'fir-connection-bd828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'keyhere',
    appId: '1:1018622800124:ios:4d8a28c1954d62c4f5a779',
    messagingSenderId: '1018622800124',
    projectId: 'fir-connection-bd828',
    storageBucket: 'fir-connection-bd828.appspot.com',
    iosBundleId: 'com.example.firebaseConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'keyhere',
    appId: '1:1018622800124:ios:4d8a28c1954d62c4f5a779',
    messagingSenderId: '1018622800124',
    projectId: 'fir-connection-bd828',
    storageBucket: 'fir-connection-bd828.appspot.com',
    iosBundleId: 'com.example.firebaseConnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'keyhere',
    appId: '1:1018622800124:web:67d47693bd3ba677f5a779',
    messagingSenderId: '1018622800124',
    projectId: 'fir-connection-bd828',
    authDomain: 'fir-connection-bd828.firebaseapp.com',
    storageBucket: 'fir-connection-bd828.appspot.com',
    measurementId: 'G-SFJS42QEPV',
  );
}
